### ISSUE TITLE
Bug ; DEAR JOB >>Web>>JOB TYPE

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#101]
Action:- Selecting all job types like part-time and full-time
Expected Output:- Should select only one job type like part-time OR full-time
Actual Output:- Accepting all job types as part-time, full-time, and contract type
![image](https://github.com/gak112/DearjobTesting2/assets/143800972/93739801-af7f-4919-b055-ed24fa7e48bf)

**Comment by QSPaysys1** [comment]
As per client requirements, Job type should be in check boxes only. So selecting one is not right as per requirement.
