### ISSUE TITLE
Bug ; DEAR JOB >>Web>>JOBSEEKER>>CURRENT^ORGANAISATION

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#106]
Action:- Both the numbers and the letters are taken in the organization
Expected Output:- An organization should be only in letters and in the words
Actual Output:- It has numbers and the words
![image](https://github.com/gak112/DearjobTesting2/assets/143800972/70eea9df-5f8e-483f-86ad-0289cda9ecba)

**Comment by QSPaysys1** [comment]
it allows both letters and numbers
