### ISSUE TITLE
Bug ; DEAR JOB >>Web>>JOBSEEKER>>JOB^PROFILE

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#108]
Action:- All the numbers, letters, and special characters are taken in the job profile
Expected Output: The job profile needs only a para about what the job seeker needs 
Actual Output:- The job profile column is accepting numbers, letters, and special characters also
![image](https://github.com/gak112/DearjobTesting2/assets/143800972/c8ae194c-f89c-4694-8637-b32619e15c3b)

**Comment by QSPaysys1** [comment]
job profile can allow numbers, letters and also special characters
