### ISSUE TITLE
 DEAR JOB WEB ,Home>posted Jobs>Post a Job ;ERROR in entering zipcode

### ISSUE THREAD

**Issue by navyabantu** [gak112/DearjobTesting2#112]
Action : In zipcode consisting only valid number they allowing other number in Zipcode

expected Output : zipcode will enter only 4-9 digits numbers

Actual Output : Zipcode taking more than number in place holder
![image](https://github.com/gak112/DearjobTesting2/assets/143584730/3705041f-0216-4522-9de9-80526e5ff334)

**Comment by QSPaysys1** [comment]
issue reolved., please check
