### ISSUE TITLE
DEAR JOB WEB ,Home>posted Jobs>Post a Job ;ERROR in live period days

### ISSUE THREAD

**Issue by navyabantu** [gak112/DearjobTesting2#114]
Action : In Live period days allowing so many numbers

Expected output : only allowed two or three digits 

Actual Output : In this place holder allowing more than digits

![image](https://github.com/gak112/DearjobTesting2/assets/143584730/e5e80f6c-b502-47be-a22a-22ae367c7bce)

**Comment by QSPaysys1** [comment]
issue resolved., please check
