### ISSUE TITLE
Bug/Suggestion/Enhancement: i Erasing Data If We Choose Some Other Option and Getting Back to Form

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#12]
When I Click on Resources and Contact Us For a Reason And Get Back to My Entered Form i Lost My All Data Which I Entered into the form, As a New User To The Application I Lost My Interest To Enter all The Form Again to Register, to make sure save the data in the form and When i Get Back It Must Be Reload The Data into The Form Which I Previously entered into the forms
![Screenshot 2023-08-30 at 7 38 25 PM](https://github.com/gak112/DearjobTesting2/assets/143583822/24569cfd-067d-4e60-9a0d-7743c6513bc1)

**Comment by QSPaysys1** [comment]
we are not saving the data before submitting, so he should complete the form .

**Comment by Hemakotibonthada** [comment]
Okay

From: Abhinav Gunda ***@***.***>
Date: Monday, 4 September 2023 at 13:26
To: gak112/DearjobTesting2 ***@***.***>
Cc: Hema Koteswara Rao Bonthada ***@***.***>, Author ***@***.***>
Subject: Re: [gak112/DearjobTesting2] Bug/Suggestion/Enhancement: i Erasing Data If We Choose Some Other Option and Getting Back to Form (Issue #12)

we are not saving the data before submitting, so he should complete the form .

**Comment by Hemakotibonthada** [comment]
Yeah Sure But Make Sure If There is a Possibility Then Automatically Save On Browser While entering the data.
