### ISSUE TITLE
Bug ; DEAR JOB >>Web>>EMPLOYER^POST A JOB

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#120]
Action:- When I entered the dear job website and posted a job in some location the zip code went wrong 
Expected Output:- Zip code should have only 4 to 6 numbers
Actual Output: The zip code of a location has many numbers 
![image](https://github.com/gak112/DearjobTesting2/assets/143800972/ee84470f-82b6-46eb-b41c-03da90699222)

**Comment by QSPaysys1** [comment]
issue reolved. please check
