### ISSUE TITLE
Bug: Dear Job Web>>Home>>Register>>Job Seeker Registration, i didn't get any toaster while click on Invalid Button

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#13]
Action:
While Clicking on Save and Next Button on The Following Path Home>>Register>>Job Seeker Registration
It Didn't Giving or Pop Any Error Message or Toaster On The Screen Where did i made a mistake When Without Entering Any Skill

Expected Output:
An Error Message or Pop up Or Toaster That Indicates **You Are Not Entered Minimum Of 3 Skills**

Actual Output:
Didn't get Any Pop Or Toaster or Notification
![Screenshot 2023-08-30 at 7 44 50 PM](https://github.com/gak112/DearjobTesting2/assets/143583822/4106a168-ba64-4a20-9e65-333d0537e104)

**Comment by QSPaysys1** [comment]
if user enters minimum of 3 skills., save & next button will enabled
