### ISSUE TITLE
Dear Job Wed^^Job Seeker^^INBOX^^ :Email Message^

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#138]
Action:- The email message was accepting all characters that are present in the keyboard 
Expected Output:- Email message should have the important text regarding to the work
Actual Output:- It was taking all the characters like numbers, letters, and the special characters
![image](https://github.com/gak112/DearjobTesting2/assets/143800972/32c366e4-d1d1-473b-916c-e51f9c3a0e22)

**Comment by QSPaysys1** [comment]
Email message should allow all  characters like numbers, letters, and the special characters
