### ISSUE TITLE
Bug: Dear Job Web>>Home>>Register>>Job Seeker Registration, Taking special characters as Name

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#14]
action:
While Entering the Name It takes What Ever you Entered Instead of Taking name or Alphabet
expected output:
a Toaster  contain a Message of Invalid Characters on Name Pannel 
actual Output: 
Taking anything as user name if they entered invalid too
![Screenshot 2023-08-30 at 7 54 46 PM](https://github.com/gak112/DearjobTesting2/assets/143583822/1907c0f5-2098-4d17-86fe-7b3b6e09b65d)

![Screenshot 2023-08-30 at 7 51 40 PM](https://github.com/gak112/DearjobTesting2/assets/143583822/c7dbc6eb-2844-4397-bdab-7cd120d235d5)

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by Hemakotibonthada** [comment]
Dear @QSPaysys1, The bug Is Partially Fixed As you Mentioned that it takes Special Characters from Clipboard Unless we type it didn't taking from key
![Screenshot 2023-09-11 at 12 57 01 PM](https://github.com/gak112/DearjobTesting2/assets/143583822/e9d4cb16-3ea9-4ef8-86a1-e96e312b14ff)
board
