### ISSUE TITLE
Bug: Dear Job Web>>Home>>Register>>Job Seeker Registration, Disappearing the location when coming from the second page

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#15]
Action: 
i Entred my Location on the page 1 of registration form and when i click on next and comming to back to 1st from the second from the location which i entered got disappeared
![Screenshot 2023-08-30 at 8 01 37 PM](https://github.com/gak112/DearjobTesting2/assets/143583822/fa194303-87d1-4b15-ae9d-556df77dded4)

**Comment by QSPaysys1** [comment]
it is google autocomplete text field., so data will not save in text field, it saves only in location badges colored in orange
