### ISSUE TITLE
Dearjob>>Web>>Employer>>Post a job

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/DearjobTesting2#155]
After i post a job, it is not updating,
it was updating only after i did screen refresh
![Job post1](https://github.com/gak112/DearjobTesting2/assets/143584298/6360fe5b-d362-444a-b906-6fccdd70fc04)

**Comment by QSPaysys1** [comment]
after posted job , posted jobs should refresh aafter post job. Its algolia refresh
