### ISSUE TITLE
DearJob >> Web >> JOB SEEKER REGISTRATION >>Bug: Basic Details

### ISSUE THREAD

**Issue by sankarnagarapu** [gak112/DearjobTesting2#156]
In basic details of job seeker registration page.

some issues with email validation. It goes to the next section without proper validation.
validations goes like:
1. it is checking to enter '@' and also telling to fill the part after that.
![1](https://github.com/gak112/DearjobTesting2/assets/144095983/4955b22c-a7e7-4bad-a7a6-a792038996d1)
![2](https://github.com/gak112/DearjobTesting2/assets/144095983/bbaeb95e-1c1c-44bd-952a-46b2efe3be92)
2. after entering single letter it stops validation and can go to the next section.
![3](https://github.com/gak112/DearjobTesting2/assets/144095983/c64920b5-f1ec-4181-81a5-1a95b202a31b)
3.after entering dot symbol , it asks to enter after that and but entering one letter it goes ok.
![4](https://github.com/gak112/DearjobTesting2/assets/144095983/6f7a0d4b-59db-4c1d-9d6b-df4e18c87e96)
![5](https://github.com/gak112/DearjobTesting2/assets/144095983/98f895a9-55ac-4061-9f39-8225215e1619)

Expected Output:
* It should check both '@' and '.' to be in email.
* it should check for text after '@' and check for at least two characters after '.'

**Comment by QSPaysys1** [comment]
Email address domain has no of Extenstions., so Email id just validate whether "@" is not
