### ISSUE TITLE
DearJob >> Web >> JOB SEEKER REGISTRATION >>Basic Details <BUG>

### ISSUE THREAD

**Issue by sankarnagarapu** [gak112/DearjobTesting2#160]
In current location field in basic details.
the text field is not taking input properly when reassigned.
### scenario:
1. i have given input text as some specific address like
![image](https://github.com/gak112/DearjobTesting2/assets/144095983/b1788db4-98ab-4446-9677-4134e8fefb48)
2. when i remove it and want to use small address like
![image](https://github.com/gak112/DearjobTesting2/assets/144095983/41f2deda-f62e-4cb4-a882-a9815004e2c8)
3. it is not overwriting the address . only changing the state and country.
![image](https://github.com/gak112/DearjobTesting2/assets/144095983/6f5f6287-6814-439f-9321-c6b922a80330)
4. if we want to reset address, we need to refresh page.

### Suggestion:
* when we made the location field empty, it should be able to remove the previous address tags below the field.

**Comment by QSPaysys1** [comment]
issue resolved

**Comment by sankarnagarapu** [comment]
yes,checked, all good.
