### ISSUE TITLE
Bug ; DEAR JOB WEB ;Home>Inbox>Reply ; Error in Inbox reply

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/DearjobTesting2#165]
Action :- After recieving the mail from person while replying to it in  the to address it is mentioning our email id not mention to whom we have to give rly 

Expected Output :- while replying to address should must be others to whom we are replying to

Actual Output :- IT is showing our email id instead of others
![image](https://github.com/gak112/DearjobTesting2/assets/143584640/d5052f19-e065-428e-8d9f-90211f618bbe)

![image](https://github.com/gak112/DearjobTesting2/assets/143584640/1ad4177e-7582-44e0-a288-9a16625b222c)

**Comment by QSPaysys1** [comment]
issue resolved., please check
