### ISSUE TITLE
Dearjob>>Web>>Employer>>Posted jobs>>Job status

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/DearjobTesting2#176]
When im trying to Disable the particular posted job
![before1](https://github.com/gak112/DearjobTesting2/assets/143584298/7aef93c7-0178-474d-89cc-47ca19a0486e)

Its working properly first
![after1](https://github.com/gak112/DearjobTesting2/assets/143584298/cd652faa-54ca-412e-8bd6-265431a02b3c)

And then later when i refreshes my screen, the status automatically droping back as before's status
![final1](https://github.com/gak112/DearjobTesting2/assets/143584298/0b35f0fd-4f99-43f1-b203-1b11a7545a9c)

**Comment by QSPaysys1** [comment]
due to algolia, refresh every time after post a job
