### ISSUE TITLE
Dear Job Web, Home>Job Seeker Details, Bug At Uploading Image With .JPEG Image Format

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#18]
Action:- I'm Trying to upload a New Image As my Profile Photo which is **.jpeg & .JPG**mostly Say Standard Image Format Over the Internet and Applications, So When I Tried to Upload it, It's Not Taking To Set my Profile picture and Saying format Doesn't Support On Pop up Error Alert Box
![Screenshot 2023-08-31 at 01 42 25](https://github.com/gak112/DearjobTesting2/assets/143583822/0c19fcb5-0d3a-4fc3-854d-b6eeef28027c)
![Screenshot 2023-08-31 at 01 43 01](https://github.com/gak112/DearjobTesting2/assets/143583822/3d2acc36-b127-4923-94f8-a0969812df72)

**Comment by QSPaysys1** [comment]
issue resolved please check

**Comment by Hemakotibonthada** [comment]
Issue Has been Cleared.
![Screenshot 2023-09-08 at 3 26 42 PM](https://github.com/gak112/DearjobTesting2/assets/143583822/331532f3-4d28-4269-b7fb-7657745fc520)
