### ISSUE TITLE
Dear Job Web, Home>Job Seeker details, Asking for Pending Email Verification

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#19]
Action:- Logged Into The User Profile Successfully By using Otp Sent to Email From the Authentication Portal, But Again I't Showing Verification Pending
Expected Output:- Nothing Is Showed There or Verified Message is Shown Because We Can Able To Enter After entered By OTP Which Is Sent to mail id
![Screenshot 2023-08-31 at 01 56 16](https://github.com/gak112/DearjobTesting2/assets/143583822/a79ec417-6bb1-47e9-b8d7-96cc2577f396)

Actual Output:- There must Be Email Verified or Nothing Showed

**Comment by QSPaysys1** [comment]
issue resolved

**Comment by Hemakotibonthada** [comment]
Dear @QSPaysys1 it's fixed
![MicrosoftTeams-image](https://github.com/gak112/DearjobTesting2/assets/143583822/5f477a0c-7d6d-4543-9c1e-b3d09cc6032c)
