### ISSUE TITLE
Dear Job Web, Home>Post a Job, Job Title Input box

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#191]
Accepecting Special Characters as Input But I Don't is There Any Special Characters in Job 
![Screenshot 2023-09-05 at 18 29 13](https://github.com/gak112/DearjobTesting2/assets/143583822/30974e08-db3f-458c-bbc6-a13e77f7d0a3)
Title

**Comment by QSPaysys1** [comment]
issue resolved please check

**Comment by Hemakotibonthada** [comment]
Dear @QSPaysys1 Issue is Cleared .
![WhatsApp Image 2023-09-08 at 15 17 37](https://github.com/gak112/DearjobTesting2/assets/143583822/0b2f1032-3327-4b40-9baf-c527b25f5ca3)
