### ISSUE TITLE
DearJob >> Web >> Subscriptions >> Billing Address <Suggestion>

### ISSUE THREAD

**Issue by sankarnagarapu** [gak112/DearjobTesting2#199]
# Back Button Navigation
* After adding addresses, the have has to click on "Payment Summary" in the route heading to navigate back to payment section.
![image](https://github.com/gak112/DearjobTesting2/assets/144095983/73018520-c7ae-4143-8b39-244231a10286)
## Suggestion
* It would be better if we place a "Back" button below the list of addresses to go back to payment.

**Comment by QSPaysys1** [comment]
iisue resolved., please check

**Comment by sankarnagarapu** [comment]
yes
