### ISSUE TITLE
Bug: Selecting Option Not Highlight While Choosing an Option

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#2]
When i Choose My Gender on Login I Didn't Get What i Choosed Because Of Same Color on Mark and Background, It's If The Background or marking Color or two different then user will easly Identified What They Choosed, Even They Can Be Rectified If They Did Make a Mistake while choosing it
![Screenshot 2023-08-30 at 6 28 45 PM](https://github.com/gak112/DearjobTesting2/assets/143583822/5506ef83-f9d9-4c43-b59d-8b0a34656c6d)

**Comment by qspaysys2** [comment]
Cleared

**Comment by Hemakotibonthada** [comment]
Hi Dear @qspaysys2 i Just Checked on WebSite But I Didn't Notice Any Change in The Bug, Can You ReVerify And Update Me brother , I'm Looking Forward To Deploy On Site As Well

![Screenshot 2023-08-31 at 00 52 09](https://github.com/gak112/DearjobTesting2/assets/143583822/bbfe590d-4499-4994-b51d-25d222f73e88)

**Comment by Hemakotibonthada** [comment]
Dear @qspaysys2, the Bug Has Been Fixed and i Approciate Your Work.
![Screenshot 2023-08-31 at 10 25 57](https://github.com/gak112/DearjobTesting2/assets/143583822/824d06b5-a385-4651-8e7f-53e08553f17f)
