### ISSUE TITLE
Bug ; DEAR JOB WEB ;Home>JobSeekerDetails ;Error in choose file 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/DearjobTesting2#204]
Action :- In choose file format i didn't select any format but  it is accepting 

Expected Output :- Mentioned format should be accept 

Actual Output :- Even withouting selecting any format it is accepting 
![image](https://github.com/gak112/DearjobTesting2/assets/143584640/d095644a-fe82-4e38-9a66-dfebb786c6e9)

![image](https://github.com/gak112/DearjobTesting2/assets/143584640/29e28db4-f0ff-472b-a1aa-f88852b766b6)

**Comment by QSPaysys1** [comment]
issue resolved., please check
