### ISSUE TITLE
DearJob >> Web >>Job Seeker^^Employment Details^Start Date and Year:: Error::

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#209]
Action:- When I entered the start date and year in the employment details the year was in a single-digit number and it was accepting
Expected Output:- Year should be correct basically in four-digit or two-digit number
Actual Output:- The year of the start is in One-digit numbers and it was accepted without raising any error

![image](https://github.com/gak112/DearjobTesting2/assets/143800972/994d4ddd-ab6d-4640-9b06-5ec9ed3618cf)

**Comment by QSPaysys1** [comment]
Done ., issue resolved please check
