### ISSUE TITLE
Dear Job Web Home>Job Seeker Details, It's Taking Invalid URL to Certificate

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#21]
Action:- I Entered an Invalid URL, But It's Accepting to Assign My Certification With URL
Expected Output:- **an Alert Msg With Please Enter a Valid URL, You Are Entered an Invalid URL**
Atcual Output:- Taking Invalid and Nothing Showing Any Alert Message
![Screenshot 2023-08-31 at 10 57 12](https://github.com/gak112/DearjobTesting2/assets/143583822/563c1d29-4d77-47bc-9bc1-468684e28ff6)

**Comment by QSPaysys1** [comment]
we are not validating any URL., we area taking data
