### ISSUE TITLE
DearJob >> Web >>Job Seeker^^Salary^^Per Hour^^#Employment:: Issue::

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#211]
Action:- When I was entering the digits in the salary per hour column it was adding too many digits where the salary per hour doesn't contain many digits
Expected Output:- Per Hour salary should be in limited digits 
Actual Output:- Accepting many digits in the salary per hour column

![image](https://github.com/gak112/DearjobTesting2/assets/143800972/d98f1f6c-5c67-4a42-bd6a-ee6206b4435d)

**Comment by Snehanama** [comment]
Action:- When I was entering the digits in the salary per hour column it was adding too many digits where the salary per hour doesn't contain many digits
Expected Output:- Per Hour salary should be in limited digits
Actual Output:- Accepting many digits in the salary per hour column

image

**Comment by QSPaysys1** [comment]
as per client requirements. we can't keep limit
