### ISSUE TITLE
DearJob >> Web >>Job Seeker Employment Details^^Adding Top 5 key skills^^Issue::

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#215]
Action:- Skills don't contain special characters here this was adding many special characters 
Expected Output:- Skills should be in the formation of words and letters
Actual Output:- It was accepting some Numbers and special characters 

![image](https://github.com/gak112/DearjobTesting2/assets/143800972/c3d5d000-e9ef-4cec-bb02-d53f499bc56c)

**Comment by Snehanama** [comment]
Action:- Skills don't contain special characters here this was adding many special characters
Expected Output:- Skills should be in the formation of words and letters
Actual Output:- It was accepting some Numbers and special characters

![image](https://github.com/gak112/DearjobTesting2/assets/143800972/7dfed2db-cbd4-4541-b8cd-94970818015c)

**Comment by QSPaysys1** [comment]
Done issue resolved., please check
