### ISSUE TITLE
DearJob >> Web >>Job Seeker Employment Details^^Describing the Profile:: Issue::

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#217]
Action:- Describing the profile contains 4000 Characters but it was accepted with only one letter 
Expected Output:- It should take a minimum of a small paragraph to describe the job
Actual Output:- Accepting the profile description with only one letter 

![image](https://github.com/gak112/DearjobTesting2/assets/143800972/cde7bcd2-aba4-4a52-a761-1e010616d82e)

**Comment by QSPaysys1** [comment]
it will accept single character also
