### ISSUE TITLE
DearJob >> Web >>Job Seeker Employment Details#Adding Education::Error::

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#218]
Action:- When I was adding a course in the education details it was saying to add the second course where it wasn't adding
Expected Output:- Expecting to add a course without any issue by the notification of adding another course or else accept the single course
Actual Output: The second course wasn't added to the column where it notified to add the second course

![image](https://github.com/gak112/DearjobTesting2/assets/143800972/4daaf13c-128e-4854-8764-e8e60c2dcaa8)

**Comment by QSPaysys1** [comment]
issue resolved., please check
