### ISSUE TITLE
Dear >> Web >> Employer Sign In >>Posted Jobs <DOUBT> <SUGGESTION>

### ISSUE THREAD

**Issue by sankarnagarapu** [gak112/DearjobTesting2#221]
# Don't Need Job Location Field
* In Post a Job Page, we have Location radio input and Job location text field.
![image](https://github.com/gak112/DearjobTesting2/assets/144095983/a75334a7-930a-4aa8-889a-59ab7188105c)

#### Doubt:
* if job is remote only , do we need job location  text input ?
* if we do not, the text field **Job location** should appear when job location type is other than **Remote only** is selected. (*Suggestion*)
* If  not, OK no problems.

**Comment by QSPaysys1** [comment]
there is no relation between 2 fields.,  as per client requirements. both location and job location should display.

**Comment by sankarnagarapu** [comment]
OK,then no issues.
