### ISSUE TITLE
DearJob >> Web >> Employer signin >> Post a Job <BUG><GLITCH>

### ISSUE THREAD

**Issue by sankarnagarapu** [gak112/DearjobTesting2#222]
# Error/Glitch in Radio Buttons input
In **Post a Job** Page,
* we have inputs for Hiring Type and Payment Type as Radio Buttons.
* I found this glitch at middle of two radio inputs when clicked.
![radio-button](https://github.com/gak112/DearjobTesting2/assets/144095983/01b08130-5ddc-4038-a4d9-7e3611ccdcde)
## Suggestion:
* I think it can be resolved by making more sapce between buttons.

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by sankarnagarapu** [comment]
Yes
