### ISSUE TITLE
BUG : Dear Job >> Web >>Staffing Consultancy> > Edit Profile> > Mobile Number> > 

### ISSUE THREAD

**Issue by navyabantu** [gak112/DearjobTesting2#249]
Action : Is taking so numbers in this mobile number place holder

Expected Output : they should be taken limited numbers 1to10 or 9 to16 must be taken

Actual Output : there adding so many numbers and successfully edited 
![image](https://github.com/gak112/DearjobTesting2/assets/143584730/5fc0f7df-4e62-4695-aa52-8b83e7643378)

**Comment by QSPaysys1** [comment]
issue resolved., please check
