### ISSUE TITLE
Dear Job Web, Home>Job Seeker Details, 

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#25]
Action:- I Entered Certification Label and it's Accepting Without Taking Multimedia File Such As Jpg, JPEG, PDF, Because If They Done a Certification They Must Have That File With them atleast a soft copy.
Expected OUTPUT:- It Should Ask, You Must Paste Your Certification File,
Actual Output:- It's Accpting To Save/ SUBMIT Without Media File
![Screenshot 2023-08-31 at 11 21 38](https://github.com/gak112/DearjobTesting2/assets/143583822/dab9379c-d1c2-458e-8afa-42f028b762a4)
![Screenshot 2023-08-31 at 11 21 56](https://github.com/gak112/DearjobTesting2/assets/143583822/204fdabb-8827-46e2-92b9-6356106e4679)

**Comment by QSPaysys1** [comment]
issue resolved

**Comment by Hemakotibonthada** [comment]
Now it's Not even Asking for certification Media File if i check in This Certification Never expire
![Screenshot 2023-09-11 at 11 21 33 AM](https://github.com/gak112/DearjobTesting2/assets/143583822/ee7cc859-76bb-4a21-8cd4-19d425f522dd)

**Comment by Hemakotibonthada** [comment]
Even Page Not Responding

https://github.com/gak112/DearjobTesting2/assets/143583822/a64062a0-5674-4b93-96e6-cd35ef768a5a
