### ISSUE TITLE
Bug ; DEAR JOB  WEB ;  Staffing Consultancy ;Home> Employer Edit Details ; Error ^^Additional Information 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/DearjobTesting2#251]
Action :- In   Additional Information >>Facebook Link
 ,GitHub Link

 , Twitter Link
 , LinkedIn Link is accepting only numbers 

Expected Output :- It should accept as link not as  numbers and when we enter only numbers it should warn 

Actual Output :- It is taking numbers and it is not showing any warning 
![image](https://github.com/gak112/DearjobTesting2/assets/143584640/54e3b731-23c0-47c5-8a69-3567ef15b9b7)

![image](https://github.com/gak112/DearjobTesting2/assets/143584640/e4837658-7be4-42f4-a77f-c891577c4e9d)

**Comment by QSPaysys1** [comment]
issue reolved., please check
