### ISSUE TITLE
Bug ; DEAR JOB WEB ; Staffing Consultancy ;Home> Employer Edit Details ;Additional Information

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/DearjobTesting2#266]
Action :-  In additional information >>Facebook Link ,GitHub ,LinkedIn Link ,Twitter Link taking numbers only 

Expected Output :- Only numbers should not allowed 

Actual Output :- It is accepting 

![image](https://github.com/gak112/DearjobTesting2/assets/143584640/c0133dc1-d151-48be-99d3-e38af82fd00e)

**Comment by QSPaysys1** [comment]
issue reolved., please check
