### ISSUE TITLE
Dear Job web, Home>Register>Job Seeker Registration

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#27]
Action:- Taking Experience of Skill is 100, It's Impossible to Have an Experince of 100 Years top any one, And As Per Government Standard No One Can Work After 60 Years, Even It's US
Expected Output:- Please Enter a Valid Experience In Years, You Might Entered More than Working age limit
Actual OUTPUT:- Even It's Taking 100 Years as Experience 
![Screenshot 2023-08-31 at 11 41 16](https://github.com/gak112/DearjobTesting2/assets/143583822/526b939e-64f2-4232-b54b-1a238a3a5834)

**Comment by QSPaysys1** [comment]
as per client req., we are taking maximum of 100 years
