### ISSUE TITLE
Dearjob Web,Home>Register>Job Seeker Registration, Taking e In Experience

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#272]
Why Alphabets Can Be Put in the Experience
![Screenshot 2023-09-11 at 10 55 20 AM](https://github.com/gak112/DearjobTesting2/assets/143583822/e57ad4dc-02a7-4b34-9efe-ad825c5a6b6d)

**Comment by QSPaysys1** [comment]
issue resolved., please check
