### ISSUE TITLE
Dearjob Web,Home>Register>Job Seeker Registration, Valid Information On Experience Column

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#273]
Experience is Not Showing After Entering e In the Years Box
![Screenshot 2023-09-11 at 10 56 42 AM](https://github.com/gak112/DearjobTesting2/assets/143583822/a2318029-c150-44f0-b9ec-f29a34a8d82f)

**Comment by Hemakotibonthada** [comment]
Here is The Another Sample for that bug
![Screenshot 2023-09-11 at 10 59 53 AM](https://github.com/gak112/DearjobTesting2/assets/143583822/294849ed-6bf5-4153-a2b6-ae9caa8a8449)

**Comment by QSPaysys1** [comment]
issue resolved., please check
