### ISSUE TITLE
Bug: Dearjob:: STAFFING CONSULTANCY REGISTRATION::Issue::

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#275]
Action:- When I was entering the company name in consultancy registration it was taking the special characters and numbers in the company name column 
Expected Output:- The company name only contains some letters which should be in the form of a name
Actual Output:- It was accepting the special characters and the numbers where the company name shouldn't be in the special characters 

![image](https://github.com/gak112/DearjobTesting2/assets/143800972/c2d420d9-97cc-47dd-9b2c-fd3c76610da7)

**Comment by QSPaysys1** [comment]
issue resolved., please check
