### ISSUE TITLE
Bug ; DEAR JOB WEB ; Home>Register>Staffing Consultancy> Registrations ;Error in Company name 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/DearjobTesting2#276]
Action :- In company name place holder it is accepting special characters when we copy paste from note pad it is accepting 

Expected Output :- It not should not accept and it have to give warning 

Actual Output :- When we are copypaste from note pad it is accepting 
![image](https://github.com/gak112/DearjobTesting2/assets/143584640/e80e7ef8-4994-4052-89c4-ab9fcba417fe)

![image](https://github.com/gak112/DearjobTesting2/assets/143584640/37298381-e85a-4aa4-a82c-3f821690165f)

**Comment by QSPaysys1** [comment]
please check issue resolved

**Comment by Dharanimaccha** [comment]
Ok sir
