### ISSUE TITLE
Bug: Dearjob:: STAFFING CONSULTANCY REGISTRATION::Contact Person Name:Issue::

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#278]
Action:- The name of the contact person in the registration is taking special characters and numbers
Expected Output:- The name shouldn't contain special characters and numbers, it should be in the form of some words
Actual Output:- The name of the person has taken some special characters indirectly when we are pasting those special characters in the column

![image](https://github.com/gak112/DearjobTesting2/assets/143800972/4a647fae-f76a-472c-864d-e09dc76ee5e6)

**Comment by QSPaysys1** [comment]
issue resolved., please check
