### ISSUE TITLE
Bug : Dear Job >>EMPLOYER REGISTRATION on Company Name . 

### ISSUE THREAD

**Issue by navyabantu** [gak112/DearjobTesting2#279]
Action : In this company name place holder near taking other special characters indirectly 

Expected Output : others characters not allowing directly

Actual Output : Allowing other characters indirectly like we wrote on notepad and copy paste in there place holders and taking successfully

Bug : Dear Job >>EMPLOYER REGISTRATION on Company Name . #271

**Comment by QSPaysys1** [comment]
issue resolved., please check
