### ISSUE TITLE
Dear Job Web, Home>Register>Job Seeker Registration, It's Didn't Accpting only remote work Location

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#28]
Action:- As Exployee, I Wanted to Work From Home For My JOB, So I Just Wanted to apply only available workfrom home and i don't wanna see other works whoes with office location jobs
expected output:- It Should Accept **Remote** Location Alos as Location
Actual Output:- Giving a Toaster That Please Type a Job Location atleast One Even Choose One Option called Remote
![Screenshot 2023-08-31 at 11 44 53](https://github.com/gak112/DearjobTesting2/assets/143583822/1c374c42-ef65-4ac3-86b1-e03f9170a429)

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by Hemakotibonthada** [comment]
Dear @QSPaysys1 Now the bug is Fixed. 
![Screenshot 2023-09-11 at 12 25 21 PM](https://github.com/gak112/DearjobTesting2/assets/143583822/b573476c-34d2-4b4e-8368-e0de82e50107)
