### ISSUE TITLE
Dearjob Web,Home>Register>Job Seeker Registration, Taking Space as OTP

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#280]
It Allows Space As Valid OTP Input Even We Provide Numbers only
![Screenshot 2023-09-11 at 11 08 03 AM](https://github.com/gak112/DearjobTesting2/assets/143583822/4a4287e0-05dd-402e-8221-39bc9a707a0f)

**Comment by QSPaysys1** [comment]
issue resolved., please check
