### ISSUE TITLE
Bug ; DEAR JOB WEB ; Home>Register>Staffing Consultancy> Registrations ; Error in contact person 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/DearjobTesting2#281]
Action :- When we enter copy paste from note pad the contact person label is accepting the special characters mentioned in the notepad 

Expected Output :- When copy paste special characters or numbers it should not accept and it  have to give the warning 

Actual Output :- So it is accepting the spl characters or numbers without giving warning 
![image](https://github.com/gak112/DearjobTesting2/assets/143584640/09f5fc29-39b3-40cd-822f-52aad60a994a)

![image](https://github.com/gak112/DearjobTesting2/assets/143584640/67b3a544-ce56-41ff-b342-e8a638d69b55)

**Comment by QSPaysys1** [comment]
issue resolved., please check
