### ISSUE TITLE
Bug:JOB SEEKER REGISTRATION: Basic Details: First Name And Last Name:: Issue::

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#282]
Action:- The name containing special characters and numbers
Expected Output:- The name should be in the letters without any issues like having some special characters in the name
Actual Output:- It was accepting some letters, special characters, and also some numbers 

![image](https://github.com/gak112/DearjobTesting2/assets/143800972/512e718b-5e44-4142-9c2d-ec239a717dfd)

**Comment by QSPaysys1** [comment]
issue resolved., please check
