### ISSUE TITLE
Bug:JOB SEEKER REGISTRATION:Educational Details::Specialisation :Issue::

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#285]
Action:- It was taking special characters in the Specialisation column
Expected Output:- Specialisation should only contain letters and digits 
Actual Output:- It was accepted to have special characters which are wrong to add special characters in the specialisation

![image](https://github.com/gak112/DearjobTesting2/assets/143800972/306bdc69-ea51-490e-beb8-c039752e48f8)

**Comment by QSPaysys1** [comment]
issue resolved please check
