### ISSUE TITLE
Dearjob>>Web>>Jobseeker>>Registration>>Employement details>>Job type

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/DearjobTesting2#286]
Current Output:- It was moving to next page even though i'm not selected any ''CONTRACT TYPE''

Expected Output:- But it shouldn't move to next page without selecting ''CONTRACT TYPE''

![test3](https://github.com/gak112/DearjobTesting2/assets/143584298/5e3eccb5-57af-4cd4-9566-0a6d75674426)

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by srinivasmudhiraj3** [comment]
Thank you @QSPaysys1
