### ISSUE TITLE
Bug : Dear Job >>EMPLOYER REGISTRATION>>Contact person Name.

### ISSUE THREAD

**Issue by navyabantu** [gak112/DearjobTesting2#287]
Action : taking special characters values  indirectly 

Expected Output : not allowing directly in this place holder only copy and paste

Actual Output : In these contact person name taking others special characters value indirectly and submitted successfully

![image](https://github.com/gak112/DearjobTesting2/assets/143584730/4be83305-b466-4801-8171-b0023d2f86f3)

**Comment by QSPaysys1** [comment]
issue reolved., please check

**Comment by navyabantu** [comment]
Ok sir
