### ISSUE TITLE
Dearjob>>Web>>Jobseeker>>Registration>>Work Authorization>>Visa type

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/DearjobTesting2#288]
Current Output:- It is moving to next page even though i enter a complete invalid VISA TYPE name.

Expected Output:- It should not validate when i enter wrong or invalid VISA TYPE.

![test4](https://github.com/gak112/DearjobTesting2/assets/143584298/ae673ac0-eba7-4e89-a310-e2b6dd24570f)

**Comment by QSPaysys1** [comment]
we are not validating any visa type. it is just input to enter

**Comment by srinivasmudhiraj3** [comment]
Okay got it @QSPaysys1
