### ISSUE TITLE
Bug:JOB SEEKER REGISTRATION:Employement Details::Designation and Organaization: Issue::

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#289]
Action:- Adding a designation and an organization with some special characteristics was accepted
Expected Output:- A designation shouldn't have those special characters
Actual Output:- Accepting special characters where they shouldn't be present in the designation and the Organization

![image](https://github.com/gak112/DearjobTesting2/assets/143800972/deadc535-fc0f-419e-9e20-0ddcfb9290c2)

**Comment by QSPaysys1** [comment]
issue resolved., please check
