### ISSUE TITLE
Bug:JOB SEEKER REGISTRATION:Employement Details::Start Date:: Issue::

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#290]
Action:- As per the calendar the year that I entered in the start date of employment details was wrong which was not present in the calendar but it was accepted
Expected Output:- It shouldn't take the wrong year or else it shouldn't accept 
Actual Output:- Taking the wrong date and year but It was accepting that

![image](https://github.com/gak112/DearjobTesting2/assets/143800972/76540cf3-1d70-4477-9479-f9b097f5211d)

**Comment by QSPaysys1** [comment]
issue resolved., please check
