### ISSUE TITLE
Dearjob Web,Home>Register>Job Seeker Registration, Taking Empty as Experience

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#291]
It's Taking Empty Experience If We Remove 0 from it.

https://github.com/gak112/DearjobTesting2/assets/143583822/e67b5695-b4bc-4769-90d9-26a161f4ad8b

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by saigovindu9666** [comment]
@QSPaysys1 cc @Hemakotibonthada  This Bug Is Now Fixed, We Appreciate Your Work
![image](https://github.com/gak112/DearjobTesting2/assets/143585230/5afd3257-4d9d-4a3c-a161-edb65b832c4c)
