### ISSUE TITLE
Dearjob>>Web>>Jobseeker>>Change password

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/DearjobTesting2#292]
Current Output:-  Even though when i entered a Valid input, But sometimes it won't giving access to submit the form.

Expected Output:- If the input was valid, it should give access to next form.

![test6](https://github.com/gak112/DearjobTesting2/assets/143584298/4c7355e8-1ecf-443d-ac2e-901281e925ef)

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by srinivasmudhiraj3** [comment]
Thank you @QSPaysys1
