### ISSUE TITLE
Bug:JOB SEEKER REGISTRATION:Edit Profile:: Start Date and End Date:: Add certificates::Issue::

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#296]
Action:- I added the same date, the starting and the ending date it was accepted while the dates were wrong
Expected Output:- Actually  the issue date should be in the past and the end date should be in the present or future
Actual Output:- Both the issue date and the ending date are the same and it was accepted on the same dates

![image](https://github.com/gak112/DearjobTesting2/assets/143800972/92cdc31d-25b8-4dee-aef2-dfc526e1abbe)

**Comment by QSPaysys1** [comment]
issue resolved., please check
