### ISSUE TITLE
Bug:JOB SEEKER REGISTRATION:Edit Profile::Top 5 key skills::: Issue:

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#297]
Action:- Skills having special characters and numbers among letters when we are pasting them instead of typing
Expected Output:- Skills or Talents should not be in the form of special characters or numbers 
Actual Output:- It was accepted with some special characters and some numbers when we are pasting them instead of typing where skills don't have special characters 

![image](https://github.com/gak112/DearjobTesting2/assets/143800972/d7768e6f-9586-4b2a-8735-623c88945d41)

**Comment by QSPaysys1** [comment]
some skills have special characters like c#, c++, .Net. Please check and update
