### ISSUE TITLE
Dearjob>>Web>>Employer>>Edit profile>>Additional Information form

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/DearjobTesting2#298]
Current Output:- It was accepting when i enter my company ESTABLISHED YEAR as 0998. i.e, approximately above 1000 years. 

Expected Output:- the ESTABLISHED YEAR should need some limitations to add in the form.

![test11](https://github.com/gak112/DearjobTesting2/assets/143584298/99d65df0-5878-4562-bc43-0caebdb91e55)

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by srinivasmudhiraj3** [comment]
Thank you @QSPaysys1
