### ISSUE TITLE
Bug: Repeated Courses

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#3]
While Choosing my Course It's Showing n number of times for the same course, Then it will be clumsy for choosing the right one and it's not good as single time appearance
The Courses Which I Faced While Registering are: 
**Masters Degree**
**bachelores Degress**
**MBA**

![Screenshot 2023-08-30 at 6 33 27 PM](https://github.com/gak112/DearjobTesting2/assets/143583822/d10b8928-3dc6-4919-b5b2-972e11faea4f)

**Comment by QSPaysys1** [comment]
Cleared, please check

**Comment by Hemakotibonthada** [comment]
Dear @QSPaysys1, I Just Checked It and Everythings Looks Fine On This Bug Right Now, i Appriciate Your Work.
![Screenshot 2023-08-31 at 00 57 15](https://github.com/gak112/DearjobTesting2/assets/143583822/09050d13-5603-473e-a82f-72b6c38c1e35)
