### ISSUE TITLE
Dearjob>>Web>>Jobseeker>>Edit profile>>Education details>>Course type

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/DearjobTesting2#306]
Current Output:- It was getting submit even i'm not entered manidatory information input.

Expected Output:- It should not get submitted without input for manidatory information.

![test16](https://github.com/gak112/DearjobTesting2/assets/143584298/e2ecb20c-993d-4055-9b87-f89d074918fb)

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by srinivasmudhiraj3** [comment]
Thank you @QSPaysys1
