### ISSUE TITLE
Dearjob>>Web>>Staffing consultant>>Registration>>Company website

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/DearjobTesting2#309]
Current Output:- It is taking a complete invalid company website.

Expected Output:- It should not take any invalid company website.

![t1](https://github.com/gak112/DearjobTesting2/assets/143584298/77959bc6-6b7c-4200-b1da-d9ae6a723275)

**Comment by QSPaysys1** [comment]
we cannot valid website domain. only we can check "https://" or "." or "www."

**Comment by srinivasmudhiraj3** [comment]
Thank you @QSPaysys1
