### ISSUE TITLE
Bug:- Dear Job>>employer>>Post a Job>>Add Billing Address

### ISSUE THREAD

**Issue by navyabantu** [gak112/DearjobTesting2#327]
Action :  taking others characters in name as on card

Expected Output : In this place holder must should take on alphabet only minimum only

Action : allowing others characters and there having submitted successfully
![image](https://github.com/gak112/DearjobTesting2/assets/143584730/c87c7a9d-2c3a-46d5-b658-49f3ab856192)

**Comment by QSPaysys1** [comment]
issue resolved., please check
