### ISSUE TITLE
Bug ; DEAR JOB WEB ; EMPLOYER ; Home >Posted Jobs : Error in posted jobs 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/DearjobTesting2#328]
Action :-  after posting a job it is not displaying in posted jobs but showing in posted job in numbers and active jobs in numbers 

Expected Output :- when the job is posted it should display in the posted jobs 

Actual Output :- it is not displayed in the posted jobs but it is showing in posted jobs and active jobs (in numbers )
![image](https://github.com/gak112/DearjobTesting2/assets/143584640/7b1beb67-9efa-4581-8fd2-218954571b7e)

![image](https://github.com/gak112/DearjobTesting2/assets/143584640/70ffb3f1-f23f-4ab8-af55-a63acd4d3816)

**Comment by QSPaysys1** [comment]
please refresh and update
