### ISSUE TITLE
Bug ; DEAR JOB WEB ; Home > Job Seeker Details > Add My Resume ;Error in Resume Name 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/DearjobTesting2#330]
Action :- when we are entering  spl characters and numbers with keyboard it is not accepting but when we are copy paste   it is accepting special characters 

Expected Output :- it should not accept when we are copy pasting or else it should give warning 

Actual Output :-  It is accepting copy paste  with out giving any  warning

**Comment by QSPaysys1** [comment]
issue resolved., please check
