### ISSUE TITLE
[WEB] [JS-Register-Mobile Number Details] Place Holder issue

### ISSUE THREAD

**Issue by sankarnagarapu** [gak112/DearjobTesting2#342]
* In this page, ```https://dearjob.org/#/auth/jsregister```.
* In the Mobile number field, place holder is "Enter your Mobile No".
* It should be "Enter your Mobile Number".

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by sankarnagarapu** [comment]
CHECKED
