### ISSUE TITLE
[WEB] [JS - Registration - Skillset Details] Experience Field issue v2

### ISSUE THREAD

**Issue by sankarnagarapu** [gak112/DearjobTesting2#355]
In the SkillSet Section of JS Registration.
* There are two fields for years and months.
* we are not able to add experience below one year firstime.
![image](https://github.com/gak112/DearjobTesting2/assets/144095983/ee9f7c8e-7f75-4e49-88f7-f37d38b5300a)
* to add below one year experience, we have remove and add zero in years field.
![image](https://github.com/gak112/DearjobTesting2/assets/144095983/63ecdb83-e8e3-4a70-b20a-c1e96dad1692)

**Comment by QSPaysys1** [comment]
We can add 0 years and 6 months in respective fields

**Comment by sankarnagarapu** [comment]
checked, closing
