### ISSUE TITLE
[WEB] [JOBSEEKER Profile] Edit Basic Details & Mobile No

### ISSUE THREAD

**Issue by sankarnagarapu** [gak112/DearjobTesting2#362]
In this page, ```https://dearjob.org/#/jobseekerprofile```.
* we can edit basic details.
* Edit Box appears but with empty fields.
![image](https://github.com/gak112/DearjobTesting2/assets/144095983/c351fb31-a013-4ed3-b814-d636a443da6d)

1. It should appear with pre-inserted our details.
2. placeholder for mobile number should be "Enter Your Mobile Number"

**Comment by sankarnagarapu** [comment]
* Just how the firstname and lastname are preinserted
![image](https://github.com/gak112/DearjobTesting2/assets/144095983/732118c2-f17a-4910-86fc-113ea0bb86f4)
* the address and phone no could be pre-feed to their fields

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by sankarnagarapu** [comment]
checked, closing.
