### ISSUE TITLE
Dearjob>>Web>>Employer>>Registration>>Company category

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/DearjobTesting2#365]
There was no Place holder for COMPANY CATEGORY, It looks better if there was a Placeholder

![image](https://github.com/gak112/DearjobTesting2/assets/143584298/36fd2fb7-de79-4bc9-b50b-7e3166349dd3)

**Comment by QSPaysys1** [comment]
Isuue resolved., please check

**Comment by srinivasmudhiraj3** [comment]
Thank you @QSPaysys1
