### ISSUE TITLE
bug : employer>>>post a job >>>job title

### ISSUE THREAD

**Issue by navyabantu** [gak112/DearjobTesting2#367]
Action : if they not allowing special characters in job title place holder

Expected Output :  mostly used special characters in job title but taken directly

Actual Output : in this place holder we enter special characters  but there not taking  in these holder and allowing copy and paste

![image](https://github.com/gak112/DearjobTesting2/assets/143584730/d3ac695f-5312-4158-9be2-1996a249b060)

**Comment by QSPaysys1** [comment]
issue resolved.,
