### ISSUE TITLE
Dearjob>>Web>>Employer>>Post a Job>>Job Title>>Issue::

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#368]
Action:- The shortcut form of a Senior Excicuter should be like Sr.Excicuter but the special character like full stop (.) was not accepted on the web but it was accepted in the mbl APK
Expected Output:-  It should take some special characters when we are entering the Job title
Actual Output:- The special characters that should be in the title of the job were not accepted to take on the web

Web:- 
![image](https://github.com/gak112/DearjobTesting2/assets/143800972/53fd633e-f991-4ce9-b148-2e2f2ced14c0)

Mobile Apk:- 
![Screenshot_20230915_161852_DearJob](https://github.com/gak112/DearjobTesting2/assets/143800972/7b73389d-5df4-440b-bec9-15745948f9b3)

**Comment by QSPaysys1** [comment]
issue resolved., please check
