### ISSUE TITLE
[WEB] [JS Profile] Address Field Duplicate <QUESTION>

### ISSUE THREAD

**Issue by sankarnagarapu** [gak112/DearjobTesting2#370]
In Profile Page of Job Seeker, 
* We have two editable Sections first and last namely "Basic Details" and "Personal Details".
* in both these sections we have address fields and what is the difference between.

https://github.com/gak112/DearjobTesting2/assets/144095983/3becfdb4-2199-4f87-b038-83ac5a4e16ee

**Comment by QSPaysys1** [comment]
user has 2 different address. 1. Current location 2. Alternate Location

**Comment by sankarnagarapu** [comment]
ok
