### ISSUE TITLE
Dearjob>>Web>>Jobseeker>>Registration>>Skill set>>Proficiency 

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/DearjobTesting2#376]
Suggestion:- There was no Placeholder for PROFICIENCY, it looks better with Placeholder.

![image](https://github.com/gak112/DearjobTesting2/assets/143584298/159a09b8-ba79-4459-a467-47edb65f71fc)

**Comment by QSPaysys1** [comment]
issue resolved

**Comment by srinivasmudhiraj3** [comment]
Thank you @QSPaysys1
