### ISSUE TITLE
Bug ; DEAR JOB WEB ; Staffing Consultancy ; Home >Users List > Add User ; Error in  Name inputs 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/DearjobTesting2#382]
Action :-  In  First name and Last name place holder it is accepting copy paste numbers and spl characters 

Expected Output :-  In place holder it should not accept spl characters even though after copy pasting or it should be warned 

Actual Output :-  Accepting and not giving any warning 
![image](https://github.com/gak112/DearjobTesting2/assets/143584640/b894440f-fe22-4d46-b469-83b889b54198)

**Comment by QSPaysys1** [comment]
issue resolved., please check
