### ISSUE TITLE
Bug ; DEAR JOB WEB ; Staffing Consultancy ; Home >Users List > Add User ; Error in Password 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/DearjobTesting2#384]
Action :-  In password it is taking normal  which is not a strong password 

Expected Output :- It should give suggestions like weak, strong password it should not accept weak passwords 

Actual Output :-  It accepting weak password without suggestion 
![image](https://github.com/gak112/DearjobTesting2/assets/143584640/a73e7b09-95b7-4a38-9f52-b57582a80e38)

**Comment by QSPaysys1** [comment]
issue resolved
