### ISSUE TITLE
Bug ; DEAR JOB WEB ; Staffing Consultancy ; Home >Users List > Add User ; Error in Phone number 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/DearjobTesting2#387]
Action :- In phone number input placeholder it is accepting many numbers 

Expected Output :- It should accept many numbers in phone number place holder and it should give the warning for entering more numbers in place holder 

Actual Output :-  It is accepting many numbers in phone number place holder without giving a warning 
![image](https://github.com/gak112/DearjobTesting2/assets/143584640/b2beb930-0ce8-4737-a731-146c1e583dad)

**Comment by QSPaysys1** [comment]
issue resolved., please check
