### ISSUE TITLE
Dear Job Web,Home>Register>Employer Registrations, Bug In Company Name Input Box.

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#39]
Action:- Entered Special Characters and Numbers In Company Name.
Expected Output:-it should give an error that it's an invalid name.
Actual O/p:- Accepting special Characters also as name of the company.
![Screenshot 2023-08-31 at 12 28 20](https://github.com/gak112/DearjobTesting2/assets/143583822/e28f641c-2bed-4d41-804c-654db37f5a87)

**Comment by QSPaysys1** [comment]
issue cleared please check. company name accept numbers and letters

**Comment by Hemakotibonthada** [comment]
Dear @QSPaysys1  Issue is Cleared
![Screenshot 2023-09-08 at 3 10 19 PM](https://github.com/gak112/DearjobTesting2/assets/143583822/cc21a880-603e-4d86-adc4-0e2806036a11)
