### ISSUE TITLE
DearJob >>Web >>Staffing Consultancy>>Posting a Job:Job Title:Issue::

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#390]
Action:- Job title taking special characters when I was pasting them in the column
Expected Output:- The job title shouldn't contain special characters whereas adding special characters may hurt job posting relevance in the eyes of search engines as they often recognize these characters as code rather than important text
Actual Output:-It was accepted to take the special characters in the job title where it can't be added

![image](https://github.com/gak112/DearjobTesting2/assets/143800972/bc2e44da-d38a-41ec-9150-ddcfe82e9d11)

**Comment by QSPaysys1** [comment]
Job title should have special characters as per standards., Employer should check before entry
