### ISSUE TITLE
Bug ; DEAR JOB WEB ;  Staffing Consultancy ; Error in Subscription ; 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/DearjobTesting2#399]
Action :- After completing registration when we take subscription it is enabling only particular time i,e., after taking subscription when enter into a another page or another additional details after filling that details is enabling that not subscribed

Expected Output :- It should not enable like that the subscription has a particular validity up to validity period it should work 

Actual Output :- But  here it is not working / applicable up to its validity time   when we enter into another page it is enabling like not subscribed but  In subscription it is showing previous history but here it showing like not subscribed 
![Screenshot 2023-09-16 122957](https://github.com/gak112/DearjobTesting2/assets/143584640/64a4a8d3-aad9-4e39-8b6e-87b0a68a2be3)
![Screenshot 2023-09-16 122846](https://github.com/gak112/DearjobTesting2/assets/143584640/0f90c9c4-bb44-4894-8dd0-5a24e861950e)

**Comment by QSPaysys1** [comment]
issue resolved., please check
