### ISSUE TITLE
[WEB] [JOB Seeker Alerts] Min Salary feature Missing

### ISSUE THREAD

**Issue by sankarnagarapu** [gak112/DearjobTesting2#403]
In Manage Alerts Page of JOB SEEKER,
* we have two fields regarding salary (MIN & MAX)
* The MAX salary field have the option to select pay time but MIN Salary doesn't have it.
![image](https://github.com/gak112/DearjobTesting2/assets/144095983/0d808d68-43da-4c09-bae8-d22fbbb6d33e)

**Comment by QSPaysys1** [comment]
Both min and max has only one salary type

**Comment by sankarnagarapu** [comment]
I think it would be good to put that selection feature seperately
If it is not that important, just comment, i'll close it
