### ISSUE TITLE
Dearjob>>Web>>Jobseeker>>Manage alerts display>>Add Alerts

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/DearjobTesting2#406]
Suggestion:- There was no placeholders for WORK EXPERIANCE, INDUSTRY and FREQUENCY.

It looks better with Placeholder.

![image](https://github.com/gak112/DearjobTesting2/assets/143584298/08354123-1ecd-4018-9250-9da1df020b81)

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by srinivasmudhiraj3** [comment]
Thank you @QSPaysys1
