### ISSUE TITLE
Dearjob>>Web>>Employer>>Post a job>>Job description

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/DearjobTesting2#425]
Current Output:- The SUBMIT Button was getting Active, even though the Mandatory stuff was not entered.

Expected output:- The SUBMIT Button should only Active when every mandatory stuff was entered.

![image](https://github.com/gak112/DearjobTesting2/assets/143584298/9a4b6ed8-faa2-4e65-870e-317d87fd55cc)

**Comment by QSPaysys1** [comment]
if button active also. with text in descrption data will not save
