### ISSUE TITLE
Bug ; DEAR JOB WEB ; Job Seeker ; Home > Inbox :;  Error in INBOX mail  Body 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/DearjobTesting2#426]
Action :- IN  mail message body when we enter a long text it is enabling one long line and the first line is taking limited text but when it comes next second line it is also accepting the long texts 

Expected Output :-  Message body input  should be in a proper way  like paragraph type 

Actual Output :- But it is taking longer text   in  one line 

![image](https://github.com/gak112/DearjobTesting2/assets/143584640/1c950983-9d63-4ce2-868f-bd635f2198d7)

**Comment by QSPaysys1** [comment]
issue resolved., please check
