### ISSUE TITLE
Dear Job Web::Inbox Message::Message Body::Issue::

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#429]
Action:- The message body has too long a line which was shown by scrolling the scroll bar at the bottom
Expected Output:- When we are writing a long message it should go to the next line 
Actual Output:- It was not going to the next line even though the message was too long it just showed the horizontal slide bad in the bottom 

https://github.com/gak112/DearjobTesting2/assets/143800972/37536f16-4fd8-4c8a-b62f-b78d38ebeb13

**Comment by QSPaysys1** [comment]
issue resolved., please check
