### ISSUE TITLE
[WEB] [Employer Sign in] Dashboard Page Company Name

### ISSUE THREAD

**Issue by sankarnagarapu** [gak112/DearjobTesting2#437]
In the DashBoard Page of Employer Sign In,
* We have Company Details at the top .
* In that, the company name which uses heading or **tag** is behaves like a anchor **a** tag.
* And it is not going to the anywhere.

https://github.com/gak112/DearjobTesting2/assets/144095983/bd8b0883-24f6-423a-ab05-a1a86228590f

* It should not show hand cursor when hovered over it. it should remain as arrow cursor.

**Comment by QSPaysys1** [comment]
issue resolved

**Comment by sankarnagarapu** [comment]
checked
