### ISSUE TITLE
Dear Job Web,Home>Register>Employer Registrations,  Bug In Contact Person Name

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#44]
**Action:-**
I Entered Numbers In The Name Input Box, But It's Didn't Restricting me to enter Numbers

**Expected Output:-**
It Must Say Name Didn't Contain Numbers

**Actual Output:-**
It Didn't Toasting Anything 
![Screenshot 2023-08-31 at 12 49 26](https://github.com/gak112/DearjobTesting2/assets/143583822/d29cccc7-85c0-47cb-8e81-3d82e4404830)

**Comment by QSPaysys1** [comment]
issue cleared please check

**Comment by Hemakotibonthada** [comment]
yeah Let me Check With Register Form.

**Comment by Hemakotibonthada** [comment]
Dear @QSPaysys1 , The Bug Remains Same In the Register form, You Reverify it once.
![Screenshot 2023-09-06 at 16 14 56](https://github.com/gak112/DearjobTesting2/assets/143583822/0de2e0f1-d5fd-4c18-9a60-ea9f594304a5)

**Comment by QSPaysys1** [comment]
company name should have numbers and letters
