### ISSUE TITLE
[WEB] [DearJob Home] No Footers in two pages

### ISSUE THREAD

**Issue by sankarnagarapu** [gak112/DearjobTesting2#440]
In Footer section of the Home page,
* we have two pages links namely **PRIVACY POLICY** and **TERMS & CONDITIONS**.
* when we go to those pages, we can't see any footer there.
* Every page in the **dearjob** have footer

https://github.com/gak112/DearjobTesting2/assets/144095983/36066c0d-d840-45b0-aad0-3453108bbcec

* we can insert the minimal footer first shown in the video into these pages

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by sankarnagarapu** [comment]
checked
