### ISSUE TITLE
[WEB] [DearJob Home] No good styling in two pages

### ISSUE THREAD

**Issue by sankarnagarapu** [gak112/DearjobTesting2#441]
In Footer section of the Home page,
* we have two pages links namely PRIVACY POLICY and TERMS & CONDITIONS.
* when we go to those pages, they don't have good styling
* I think one is route heading aligned to left 
* second is paragraph's don't have much padding
* the para container have a scroll bar but it is usable

https://github.com/gak112/DearjobTesting2/assets/144095983/ee6f6785-898e-424b-9d12-7075a9f83d07

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by sankarnagarapu** [comment]
* padding and scrollbar issues resolved
* but the breadcrumb i mean **Home > Privacy Policy** is strictly aligned to left with no margin
* if it is not important, comment again, i'll just close it.
