### ISSUE TITLE
Dearjob>>Web>>Jobseeker>>Edit profile>>Select salary type

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/DearjobTesting2#443]
Current output:- The form was get submitting even though i was not selected SALARY TYPE.

Expected output:- The Form should not submit, without select SALARY TYPE along with EXPECTED SALARY.

Image 1
![image](https://github.com/gak112/DearjobTesting2/assets/143584298/6a6f0b67-234c-4007-8f5b-2e1eeae81537)

Image 2
![image](https://github.com/gak112/DearjobTesting2/assets/143584298/f4c81284-0044-4918-8989-c9718574996d)

**Comment by QSPaysys1** [comment]
it is not mandatory field
