### ISSUE TITLE
Dearjob>>Web>>Employer>>Registration>>Password

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/DearjobTesting2#45]
Not asking password strength, so anyone can hack tmy account easily, so kindly please check it

![Screenshot '](https://github.com/gak112/DearjobTesting2/assets/143584298/8981308b-34f4-4845-adec-40ec450e930f)

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by srinivasmudhiraj3** [comment]
Thank you @QSPaysys1
