### ISSUE TITLE
Dear Job Web,Home>Register>Employer Registrations,  Bug In Company  Category Input Text Box

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#46]
**Action**:-
I Entered Numbers In The Name Input Box, But It's Didn't Restricting me to enter Numbers

**Expected Outpu**t:-
It Must Say on Toaster that 

Name Didn't Contain Numbers

**Actual Output:**-
It Didn't Toasting Anything

![Screenshot 2023-08-31 at 12 54 59](https://github.com/gak112/DearjobTesting2/assets/143583822/14640cbe-b0f2-4aae-88bc-41db892048b0)

**Comment by QSPaysys1** [comment]
Cleared

**Comment by Hemakotibonthada** [comment]
Yeah Dear @QSPaysys1 , The Bug Is fixed
![Screenshot 2023-08-31 at 13 04 56](https://github.com/gak112/DearjobTesting2/assets/143583822/d5137d92-12a7-4cad-bbed-0c018a6a6efd)
