### ISSUE TITLE
BUG ; DEARJOB ADMIN ; Masters  > Universities > Add Universities :; Error in University 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/DearjobTesting2#460]
Action :- IN add  University it is taking  Special characters and numbers and also accepting copy paste

Expected Output :- University  name should in alphabets and it should warn when we enter  Special characters and copy paste  

Actual Output :- But it is accepting  the special characters numbers and copy paste  
![image](https://github.com/gak112/DearjobTesting2/assets/143584640/5eb69944-5c29-49d3-87dc-a30e72fe4f5c)

**Comment by QSPaysys1** [comment]
there is a possibility of special characters & numbers in universities names
