### ISSUE TITLE
Dear Job Admin: In Masters:: The Company Categories:: Multiple Catogories Added In Admin Page::Issue::

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#461]
Action:- There are multiple categories were added to the company categories 
Expected Output:- It should only allow one category in the admin page of the dear job
Actual Output:- There are some categories that are repeated for some time and accept the multiple categories in the admin page

![image](https://github.com/gak112/DearjobTesting2/assets/143800972/341e62f1-ca32-4f53-b0dd-da039decbf1e)

**Comment by QSPaysys1** [comment]
issue resolved., please check
