### ISSUE TITLE
BUG ; DEARJOB ADMIN ; Masters > Languages > Add Languages :;

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/DearjobTesting2#463]
Action :-  It is accepting same language after entering the same language at once 

Expected Output :- It should only  accept one language at once  and it should give warn after entering same language 

Actual Output :- But here it is accepting the same language  at once 
 
![image](https://github.com/gak112/DearjobTesting2/assets/143584640/b0638247-86c8-4ded-84b1-0eaac69e8f22)

**Comment by QSPaysys1** [comment]
issue resolved., please check
