### ISSUE TITLE
BUG ; DEARJOB ADMIN ; Masters > Languages > Add Languages :;  Taking Special Characters ;

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/DearjobTesting2#465]
Action :- IN add languages label input  it is accepting the special characters and numbers and also copy paste 

Expected Output :- It should not accept the Special characters and numbers in language input label and when we copy paste it should must give warn 

Actual Output :-  But accepting the Special characters and numbers 

![image](https://github.com/gak112/DearjobTesting2/assets/143584640/1f5ca69f-ffa0-4fae-979d-c78f909b076c)

![image](https://github.com/gak112/DearjobTesting2/assets/143584640/ca1286ec-dc48-4a82-ae71-5624d6c1c368)

**Comment by QSPaysys1** [comment]
issue resolved., please check
