### ISSUE TITLE
Dear Job Admin::Bug:: Adding Languages In Masters Of Admin :Issue::

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#468]
Action:- Languages are added Multiple times and also accept special characters in the language name  
Expected Output:- It shouldn't allow to addition single name as multiple and it shouldn't have special characters in the language name
Actual Output:- One Language name is added multiple times and also accepted to have special characters in the name of the language

![image](https://github.com/gak112/DearjobTesting2/assets/143800972/05a9e18f-22c0-4276-9c22-f6884e367da7)

**Comment by QSPaysys1** [comment]
issue resolved., please check
