### ISSUE TITLE
BUG ; DEARJOB ADMIN ; Masters > Company Category > Add category :; 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/DearjobTesting2#475]
Action :- In add category  it is only taking 1 alphabet with out warning 

Expected Output :- it should not accept 1 alphabet and it should  give the warning to use maximum characters 

Actual Output :-  It is accepting single alphabet without giving warning 
![image](https://github.com/gak112/DearjobTesting2/assets/143584640/ba2cae2a-5097-4854-9060-6a25ef7b53b0)

**Comment by QSPaysys1** [comment]
issue resolved., please check
