### ISSUE TITLE
Bug: Same Issue Which i Mentioned Before

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#5]
i didn't get noticed which i selected because of same color for choosing the option, it's same for course type
so make sure change the mark and options Background color, Then It's Better for Reducing By Mistake Clicks
![Screenshot 2023-08-30 at 6 45 34 PM](https://github.com/gak112/DearjobTesting2/assets/143583822/a474c164-b806-4d3e-93e6-f63c6fd2598b)

**Comment by qspaysys2** [comment]
Cleared

**Comment by Hemakotibonthada** [comment]
Dear @qspaysys2 , I Just Checked This Bug and It Remains Same As Before, Just ReVerify Once And Let Me Know If Bug is Fixed.
![Screenshot 2023-08-31 at 00 59 15](https://github.com/gak112/DearjobTesting2/assets/143583822/6c4b0e08-8513-4a23-b16d-4861366dfeef)

**Comment by Hemakotibonthada** [comment]
It's Fixed @qspaysys2 @gak112
![Screenshot 2023-08-31 at 10 25 57](https://github.com/gak112/DearjobTesting2/assets/143583822/eb3d4b51-c56f-4eeb-bc02-f539b2b3c602)
