### ISSUE TITLE
Dear Job Web,Home>Register>Employer Registrations,  Loading Module Not Activated On Submit Button

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#51]
**Action:-**
As a User i should Know What Happned Virtually Something like loading

**Expected Output:-**
Some Loading Module Must Be Activated on Submit Button And Every Button Where there is Loading and Moving to the next page
**Actual Output:-**
not Activated any Loading Module to Know It's Loading or not.
![Screenshot 2023-08-31 at 13 26 15](https://github.com/gak112/DearjobTesting2/assets/143583822/5187bf4f-e946-41e0-a9ad-8b767db1167a)

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by Hemakotibonthada** [comment]
Dear @QSPaysys1 As of now I Can't Able to Verify Because my Internet is Fast Enough To Move to the next page so i can't able to Watch the loading module , But i Took Information that were added to the code So I'm Gonna Close the ticket right now.
![Screenshot 2023-09-11 at 12 57 01 PM](https://github.com/gak112/DearjobTesting2/assets/143583822/bc7eb826-8f12-44fe-843e-4399f89e32f1)
