### ISSUE TITLE
bug:dearjob>web>job seeker registration> basic details >email Id

### ISSUE THREAD

**Issue by rajpurohitpremkumar** [gak112/DearjobTesting2#520]
Action:- when a user is entering email id it is accepting email id entirely in a numerical format 
Expected result :-email id should not accept totally numerical format email id 
  
![image](https://github.com/gak112/DearjobTesting2/assets/145768728/90bb46d4-96eb-4e72-ab44-318dd4e380e1)

**Comment by QSPaysys1** [comment]
Email address must have "@"
