### ISSUE TITLE
bug:dearjob>web>job seeker registration>basic details>password>confirm password

### ISSUE THREAD

**Issue by rajpurohitpremkumar** [gak112/DearjobTesting2#521]
Action:- when a user is typing one kind of  password  and  entering another kind of  words in confirm password it is not throwing message as "confirm password and password must be same 
Expected result :-Note:-confirm password and password must be same should be mentioned   below the password text field
Actual result :-It is not showing any note message while entering different passwords in password text field and confirm password text field

![image](https://github.com/gak112/DearjobTesting2/assets/145768728/4e2176c2-6998-4a58-999d-b3004c7eaa80)

**Comment by QSPaysys1** [comment]
it is validating when you enter save & next
