### ISSUE TITLE
bug; dear job>web>home>job seeker registration>basic details >email id  

### ISSUE THREAD

**Issue by rajpurohitpremkumar** [gak112/DearjobTesting2#523]
Action:- when a user is entering an email id before @symbol if a user is entering any special symbol before @ symbol like? /
Expected result:-email id should accept only one special charecter i.e @  
Actual result:-email id is accepting question mark ,slashes ,it is accepting two special charecters 
![image](https://github.com/gak112/DearjobTesting2/assets/145768728/86d32db0-5f50-4da8-85c7-e09049104ee3)

**Comment by QSPaysys1** [comment]
Email address must have "@"
