### ISSUE TITLE
Dearjob>>Web>>Jobseeker>>Profile>>upload Image

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/DearjobTesting2#53]
Im unable to upload a image, even they are in right formate like jgp,png,gif

![Image2](https://github.com/gak112/DearjobTesting2/assets/143584298/a94ee8ee-f8fa-4d98-a767-46e8d3bb061a)

**Comment by QSPaysys1** [comment]
issue resolved., please check
