### ISSUE TITLE
bug:>dear job>jobseeker>education details >skillset>save& next

### ISSUE THREAD

**Issue by rajpurohitpremkumar** [gak112/DearjobTesting2#533]
Action:-when a user is entering all the details in the skillset  after entering that it is not accepting the next button
Expected Result:- when a user is entering all the details after clicking on all options it should the save& next  button it should proceed for further
Actual Result:-it is not getting clicked on save& next button

https://github.com/gak112/DearjobTesting2/assets/145768728/564e57d5-09e7-4dc1-a6d6-576ec4179dee

**Comment by QSPaysys1** [comment]
skills should be minimum of 3 skills., if less than 3 skills button should be  disabled
