### ISSUE TITLE
Dear Job Web,Home>Register>Employer Registrations,  Bug On Company Website Name Input Text Box

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#54]
**Action:-**
Website Input Text Box Not Validating Website Formats and Taking Invalid Names Too

**Expected Output:-**
It Shoud Genarate Error

**Actual Output:-**
Not Genarating Error, Instead Of this, it Taking Invalid Inputs.
![Screenshot 2023-08-31 at 15 16 31](https://github.com/gak112/DearjobTesting2/assets/143583822/735fb144-5754-4cf3-9069-97bbb4e4d2df)

**Comment by QSPaysys1** [comment]
issue resolved
