### ISSUE TITLE
Enhancement: Missing Few Common Skill Sets.

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#6]
It's a Most Common And Basic Skill Set Called C Programming But It's not Present In the Skillset Dropdown Box, Make Sure skill sets are Wide Range skills
i entered 3 skills upto now, but those didn't Listed in The Skill sets but They are i Can Open To Add As New:
i Entered Skill sets are : **C Programming and Embedded Systems and Software Developing Engineer**
![Screenshot 2023-08-30 at 6 51 03 PM](https://github.com/gak112/DearjobTesting2/assets/143583822/2b4a7580-ef14-44c4-9ac3-0856e5111b39)

**Comment by QSPaysys1** [comment]
If skill is not exist., you can enter the skill in skill set
