### ISSUE TITLE
Dear Job Web,Home>Register>Employer Registrations,  Bug On OTP Input Text Box

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#61]
**Action:-**
Taking Unlimited Numbers AS OTP Instead Of 4
**Expected Output:-**
taking only 4

**Actual Output:-**
Taking infinity numbers
![Screenshot 2023-08-31 at 15 40 26](https://github.com/gak112/DearjobTesting2/assets/143583822/4e870766-c2fd-42e2-9bf8-288d133cc092)

**Comment by QSPaysys1** [comment]
issue resolved
