### ISSUE TITLE
Dear Job Web,Home>Register>Employer Registrations,  Bug On OTP Input Text Box

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#62]
**Action:-**
Taking Special Characers and Alphabets too

**Expected Output:-**
Only Limited to 4 Digit Numbers Only
**Actual Output:-**
All Are Open To Entered to The input Text Box 
![Screenshot 2023-08-31 at 15 40 26](https://github.com/gak112/DearjobTesting2/assets/143583822/8f86a3d5-7f61-49ad-be3c-a7b4f6d86b7c)

**Comment by QSPaysys1** [comment]
issue resolved
