### ISSUE TITLE
DEARJOB WEB, Home>Register>Job Seeker> Registration, check Error on company logo

### ISSUE THREAD

**Issue by navyabantu** [gak112/DearjobTesting2#67]
Action : They have limited supported formats only four but there supporting varies kinds of formats in company logo

Expected Output : In these company logo they should not allow the other formats only.png, .jpg, .jpeg, .gif

Actual Output : Is this supporting formats are WPS , EPS and SVG would be executed in company logo there are wrong formats and there showing save&next

**Comment by QSPaysys1** [comment]
please check issue resolved

**Comment by navyabantu** [comment]
Ok sir

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
