### ISSUE TITLE
Bug: Issue With The Toaster Message

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#7]
When i Enter a Same Skill For The Second Time The Toaster Message Saying **Please Enter Skill** Instead Of **Please Enter a New Skill or The Skill Is Already Entered** By Removing The Skill Which I Entered,
So If Entered 50 Skills And again Newly Entered The Same Skill It's Just Disaapred The Old Skill and Giving a Toaster on The Screen, So There is a Possibilty to forget What i Entered Last time, So Make Sure It's Must Be Visible and Toaster message Appeared Reg The Error
![Screenshot 2023-08-30 at 6 57 08 PM](https://github.com/gak112/DearjobTesting2/assets/143583822/c8736fce-64e4-4e20-8859-e9f43682ee86)

**Comment by QSPaysys1** [comment]
label and toasters are entered as client req
