### ISSUE TITLE
Dear Job Web,Home>Register>Staffing Consultancy Registrations, Bug in Company Contact Person Text Box

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#70]
Taking All Character, Instead of Only Text
![Screenshot 2023-08-31 at 17 09 56](https://github.com/gak112/DearjobTesting2/assets/143583822/bd96de6f-c938-49b9-8219-18dd0e62b8a8)

**Comment by QSPaysys1** [comment]
issue resolved
