### ISSUE TITLE
Bug: Issue with taking 0 months Experience

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#8]
as a student i don't have Experience On Certain Skill But I Know How Everthing works but i'm fresher for that skill 
So When i Entered The Skill with 0 Years and 0 Months, With Basic Understanding Proficiency It Didn't allow me to register the skill to the database/Profile
![Screenshot 2023-08-30 at 7 04 52 PM](https://github.com/gak112/DearjobTesting2/assets/143583822/b7424ae3-4cf5-4d03-913c-e269f551f319)

**Comment by QSPaysys1** [comment]
Even skill should have minimum  few months experience., if user have  0 years and 0 months you should not enter. please check and clear issue

**Comment by Hemakotibonthada** [comment]
Yeah Sure


From: Abhinav Gunda ***@***.***>
Date: Monday, 4 September 2023 at 13:18
To: gak112/DearjobTesting2 ***@***.***>
Cc: Hema Koteswara Rao Bonthada ***@***.***>, Author ***@***.***>
Subject: Re: [gak112/DearjobTesting2] Bug: Issue with taking 0 months Experience (Issue #8)

Even skill should have minimum few months experience., if user have 0 years and 0 months you should not enter. please check and clear issue

**Comment by Hemakotibonthada** [comment]
Dear @QSPaysys1 , Issue Solved By The Information You Provided.
