### ISSUE TITLE
Bug ; DEAR JOB APK , Employer Registration ; Error in contact name

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/DearjobTesting2#84]
Action :- accepting the special characters in contact person name

Expected Output :- Any special characters are not allowed 

Actual Output :- Accepting the speical characters
![MicrosoftTeams-image (3)](https://github.com/gak112/DearjobTesting2/assets/143584640/82ce1cf8-35b0-40f4-83a2-25b829515154)

**Comment by QSPaysys1** [comment]
please issue & close the ticket
