### ISSUE TITLE
Bug: It Saying Sent Mail Even Never Existed Mail Id

### ISSUE THREAD

**Issue by Hemakotibonthada** [gak112/DearjobTesting2#9]
It Saying That Otp Send For Invaild Mail Address Even Never Existed In Google Database too Instead of Saying Invalid Email Address On Toaster
![Screenshot 2023-08-30 at 7 28 59 PM](https://github.com/gak112/DearjobTesting2/assets/143583822/649763a4-e3da-4dae-891c-3e52d73a58dc)
![Screenshot 2023-08-30 at 7 28 50 PM](https://github.com/gak112/DearjobTesting2/assets/143583822/c5a0594f-09f3-4eaf-ab5b-f47e4f1af632)

**Comment by QSPaysys1** [comment]
In email address we are validating only "@"
