### ISSUE TITLE
Dearjob>>Web&mobile>>Edit profile>>Skill set

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/DearjobTesting2#91]
Once i registered in mobile ap[plication, and then i try to add my skillset at edit profile in mobile itself, its wont't submiting and i tried the same thing also in web, same happening

Mobile app
![Screenshot_20230901_124508 (1)](https://github.com/gak112/DearjobTesting2/assets/143584298/e8835795-2c7e-4f6f-8794-9ad03214adef)

Web
![image0](https://github.com/gak112/DearjobTesting2/assets/143584298/4930f5fb-f89c-4e27-a3e4-39855de938b7)

**Comment by QSPaysys1** [comment]
iisue resolved., please check

**Comment by srinivasmudhiraj3** [comment]
Thank you @QSPaysys1
