### ISSUE TITLE
 DEAR JOB APK ;Employer registration ;ERROR in company name

### ISSUE THREAD

**Issue by navyabantu** [gak112/DearjobTesting2#96]
Action : Is taking more than 4 letter and adding numerical  number 

Expected Output : there is only we can apply limited characters

Actual Output : in this place holder use only alphabet letter but they taking numerical numbers proceeded next 

![MicrosoftTeams-image (1)](https://github.com/gak112/DearjobTesting2/assets/143584730/d4e9812f-caee-4049-871d-4efe7abf1887)

**Comment by QSPaysys1** [comment]
issue is resolved., please check
