### ISSUE TITLE
DEAR JOB APK ;Employer registration ;ERROR in company contact person name

### ISSUE THREAD

**Issue by navyabantu** [gak112/DearjobTesting2#98]
Action : in this place holder taking numerical number

expected Output : other characters are not allowed

Actual Output : allowing the other character value 
![MicrosoftTeams-image (2)](https://github.com/gak112/DearjobTesting2/assets/143584730/8a0215d0-7177-4bff-afab-39cd75b3039f)

**Comment by QSPaysys1** [comment]
company name will Should have letters and Alphabets
