### ISSUE TITLE
Dearjob>>Web>>JOBSEEKER>>NAME

### ISSUE THREAD

**Issue by Snehanama** [gak112/DearjobTesting2#99]
Action:- Name Contains Only Words But Here Numbers Are Also Taking
Expected Output:- Name should be in Alphabet letters
Actual Output:- It was Accepted to have some numbers in the middle of the name 
![image](https://github.com/gak112/DearjobTesting2/assets/143800972/784ebc3f-6e8b-44a5-bdd7-ce479aea1e57)

**Comment by QSPaysys1** [comment]
please check., issue is resolved
